name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  connectivity_plus: ^6.1.4
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/Cloudy.json
    - assets/animations/Part-Rain.json
    - assets/animations/Snow.json
    - assets/animations/Sunny.json
    - assets/animations/ThunderStorm.json
    - assets/animations/Loading.json
    - assets/icons/logo.png

flutter_native_splash:
  color: "#2194f3"
  image: assets/icons/logo.png
  color_dark: "#2194f3"
  image_dark: assets/icons/logo.png

  android_12:
    color: "#2194f3"
    image: assets/icons/logo.png
    color_dark: "#2194f3"
    image_dark: assets/icons/logo.png